# Generated by Django 6.0.3 on 2026-04-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apply_gst',
            field=models.BooleanField(default=True),
        ),
    ]
