# Generated by Django 6.0.3 on 2026-06-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='short_code',
            field=models.CharField(blank=True, help_text='Fast code for billing searches', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prep_status',
            field=models.CharField(choices=[('IN_PREPARATION', '🍳 In Preparation'), ('WAITING_FOR_PICKUP', '📦 Waiting For Pickup'), ('OUT_FOR_DELIVERY', '🛵 Out For Delivery'), ('COMPLETED', '🏁 Completed')], default='IN_PREPARATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Cooking instructions (e.g., Less spicy)'),
        ),
    ]
