# Generated by Django 6.0.3 on 2026-04-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_order_apply_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('CASH', '💵 Cash'), ('UPI', '📱 UPI / QR'), ('CARD', '💳 Card')], max_length=10, null=True),
        ),
    ]
