# Generated by Django 6.0.3 on 2026-06-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_menuitem_short_code_order_prep_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
