# Generated by Django 6.0.3 on 2026-06-03 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_orderitem_name_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
