# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_remove_orderitem_name_remove_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(
                blank=True,
                choices=[
                    ('CASH', '💵 Cash'),
                    ('ONLINE', '📱 Online/UPI'),
                    ('CARD', 'Card'),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
