# Generated by Django 6.0.3 on 2026-06-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.CharField(choices=[('FINE_DINE', 'Fine Dine'), ('BALCONY', 'Balcony'), ('OTHER', 'Other')], default='FINE_DINE', max_length=20),
        ),
    ]
