# Generated by Django 5.2.7 on 2026-06-13 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_table_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='zone',
        ),
        migrations.CreateModel(
            name='UploadedMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_scans/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_menus', to='pos.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_items', to='pos.uploadedmenu'),
        ),
    ]
