# Generated by Django 6.0.3 on 2026-04-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_order_grand_total_order_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENT', 'Percentage')], default='FIXED', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
