# Generated by Django 5.2.7 on 2026-07-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_addon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='addons',
            field=models.ManyToManyField(blank=True, related_name='ordered_items', to='pos.addon'),
        ),
    ]
